
name: Ubuntu 20.04 LXQT
run-name: Ch√†o m·ª´ng ${{ github.actor }} ƒë·∫øn v·ªõi Rinne VPS üöÄ
on:
  workflow_dispatch:
    inputs:
      ps:
        description: 'M·∫≠t kh·∫©u ng∆∞·ªùi d√πng'
        required: true
      os:
        description: 'Nh·∫≠p m√£ Debian Linux ·ªü Chrome Remote Desktop'
        required: true
      os2:
        description: 'Nh·∫≠p PIN (6 s·ªë tr·ªü l√™n)'
        required: true
jobs:
  Ubuntu_2004_LXQT:
    timeout-minutes: 360
    runs-on: ubuntu-20.04
    steps:
    - name: T·∫£i file c·∫•u h√¨nh...
      uses: actions/checkout@v3
    - name: ƒêang x√°c nh·∫≠n m√£ Debian Linux
      run: |
           echo ƒêang ƒë·ªïi m·∫≠t kh·∫©u th√†nh HI·ªÇN TH·ªä M·∫¨T KH·∫®U ƒê√É B·ªä XO√Å V√å L√ç DO B·∫¢O M·∫¨T

         
           sudo useradd -m runneradmin &>/dev/null &
           echo 'runneradmin:${{ github.event.inputs.ps }}' | sudo chpasswd &>/dev/null &
           sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd &>/dev/null &
           sudo useradd -m runner &>/dev/null &
           echo 'runner:${{ github.event.inputs.ps }}' | sudo chpasswd &>/dev/null &
           sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd &>/dev/null &
           echo T√™n ng∆∞·ªùi d√πng l√†: runneradmin ho·∫∑c runner
           echo M·∫≠t kh·∫©u l√†: HI·ªÇN TH·ªä M·∫¨T KH·∫®U ƒê√É B·ªä XO√Å V√å L√ç DO B·∫¢O M·∫¨T
         
           bash bash1.sh
           ${{ github.event.inputs.os }} --pin=${{ github.event.inputs.os2 }} &>/dev/null 
    - name: Tr∆∞·ªõc khi k·∫øt n·ªëi VPS, b·∫°n ph·∫£i ch·ªù cho √¥ n√†y ch·∫°y xong!
      run: |
           bash lxqt-new.sh
    - name: Th√†nh c√¥ng!
      run: yes T·∫°o th√†nh c√¥ng VPS!
      timeout-minutes: 360
